### ISSUE TITLE
unclear when bz_scrubTracking should be used

### ISSUE THREAD

**Issue by raltodo** [ayalab1/neurocode#5]
The description is sparse: "this functions takes the unedited *.csv exported from Motive, smoothes and resorts columns to match the position tracking formatting standards". It is unclear to me what "Motive" is in this context (a particular acquisition software?) and based on the date, I would say this function is obsolete.

**Comment by ryanharvey1** [comment]
I agree, lets delete. I believe that function caused the wild interpolation on the legacy data with poor tracking.

**Comment by AntonioFR8** [comment]
yes, this is obsolete

**Comment by raltodo** [comment]
Removing function.
