### ISSUE TITLE
concatenateDats uses sessionTemplate for extracellular recording parameters

### ISSUE THREAD

**Issue by lolaBerkowitz** [ayalab1/neurocode#9]
Starting on line 158 - session is loaded and if none exists, one is created using the template. 

Critical info such as sampling rate is derived from session. Leading to inaccurate timestamps in MergePoints.timestamps when recording parameters diverge from sesstionTemplate defaults. 

Suggested fix is loading XML or RHD to obtain parameters.

**Comment by raltodo** [comment]
Fixed! Thanks for flagging this!
